name: Call Infrastructure

on:
  push:
    branches:
      - main

jobs:
  first-commit:
    if: github.event.head_commit.message == 'first commit'
    runs-on: ubuntu-latest
    steps:
      - name: Call Infrastructure Repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_INFRA_PAT }}
          repository: hilton98/infra-dm
          event-type: create-structure-dm-app

  deploy:
    if: github.event.head_commit.message != 'first commit'
    runs-on: ubuntu-latest
    steps:
      - name: Call Infrastructure Repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_INFRA_PAT }}
          repository: hilton98/infra-dm
          event-type: deploy-dm-app
